packages:
  - example
# patchedDependencies:
#   react-native-reanimated@4.3.1: patches/react-native-reanimated@4.3.1.patch

catalog:
  "react-native": 0.83.9
  "react": 19.2.0
  "react-native-gesture-handler": ^2.31.2
  "@jamesacarr/eslint-formatter-github-actions": "^0.1.0"
  "@react-native-community/eslint-config": "^3.0.2"
  "@release-it/conventional-changelog": "^5.0.0"
  "@types/jest": "^29.5.13"
  "@types/react": "^19.2.0"
  "@typescript/native-preview": "^7.0.0-dev.20260421.2"
  "clang-format": "^1.8.0"
  "eslint": "^8.57.0"
  "eslint-config-prettier": "^8.5.0"
  "eslint-plugin-prettier": "^4.0.0"
  "jest": "^29.6.3"
  "pod-install": "^0.3.4"
  "prettier": "^2.0.5"
  "react-native-builder-bob": "^0.41.0"
  "react-native-worklets": "^0.8.3"
  "release-it": "^20.0.0"
  "typescript": "^5.8.3"
  "@eslint/compat": "^1.1.1"
  "@eslint/eslintrc": "^3.1.0"
  "@eslint/js": "^9.9.0"
  "react-native-reanimated": "4.3.1"
